### ISSUE TITLE
Confusion over what U8glib is for

### ISSUE THREAD

**Issue by gwideman** [MarlinFirmware/U8glib-HAL#17]
Could someone please add to the README.md page a description of exactly what use-cases this library is for, and whether it is required or optional for those cases? The blurb on https://github.com/MarlinFirmware says "Customized U8glib for use in Marlin 2.0"... which leads one to believe that it might be required for Marlin 2.0. But then the README says "AVR, Arduino & Due access to the library is not changed." Does that mean that the actual library functions are the same as regular U8glib, which might already be installed in the Arduino libraries? Or should this U8glib-HAL always be used for Marlin 2.0, in which case how to install it?
Also, what is "non-native". If that means "compiling in an environment other than Arduino", please spell that out.  Thanks.

**Comment by thinkyhead** [comment]
The Marlin copy of u8glib (1.x) is slightly extended so it can support some display types that are not included with the vanilla version of u8glib (1.x). A direct comparison of the original to our slightly altered version is the simplest way to see all the differences.

The library will be automatically used when building with PlatformIO. If building with Arduino, install u8glib-HAL just as you would install any other library (download and unzip it into your `Sketchbook/libraries` folder).
