### ISSUE TITLE
https://github.com/MarlinFirmware/U8glib-HAL/archive/bugfix.zip : error 404

### ISSUE THREAD

**Issue by yet-another-average-joe** [MarlinFirmware/U8glib-HAL#19]
Hello,

It seems the U8glib-HAL library for Marlin bugfix disappeared.

Compiling Marlin (VSCode + PIO) gives this error :

`FDUnrecognizedStatusCode: Got an unrecognized status code '404' when downloaded https://github.com/MarlinFirmware/U8glib-HAL/archive/bugfix.zip`

typing "https://github.com/MarlinFirmware/U8glib-HAL/archive/bugfix.zip" in a browser also gives a 404 error (and by the way this link is a broken link)

As a result, U8glib-HAL is not installed.

Never had this issue before... Was a "archive" or "bugfix" branch recently removed from this repo ?

**Comment by richbria** [comment]
I just got here due to the same problem when attempting to use Marlin Firmware Auto Build to build for a sanguino1284p.

**Comment by richbria** [comment]
Looks like the bugfix branch was merged in here so it is probably actually an issue with Auto Build.  @yet-another-average-joe did you get here using Auto Build as well?

https://github.com/MarlinFirmware/U8glib-HAL/pull/18

**Comment by richbria** [comment]
I am incorrect. This is a problem with platforio.ini in Marlin 2.0.  I'm working on a fork now.

**Comment by yet-another-average-joe** [comment]
OK ! bugfix branch is back !
I was just attempting to compile while thinkyhead was updating the repo.
