### ISSUE TITLE
arduino ide and U8glib-HAL

### ISSUE THREAD

**Issue by ellensp** [MarlinFirmware/U8glib-HAL#26]
Add a library.properties file into this repository so Arduino IDE users can just drop this version of the library into their Arduino/libraries folder to provide Marlin with the correct U8glib-hal required to compile.   

Example library.properties here https://github.com/MarlinFirmware/Marlin/files/6710738/library.properties.zip

Related issues:
https://github.com/MarlinFirmware/Marlin/issues/22218
https://github.com/MarlinFirmware/Marlin/issues/21967
https://github.com/MarlinFirmware/Marlin/issues/21948
https://github.com/MarlinFirmware/Marlin/issues/21995

**Comment by ellensp** [comment]
It seems from https://github.com/MarlinFirmware/Marlin/issues/22303#issuecomment-876884696 you have elected to continue fighting with Arduino-IDE

**Comment by ellensp** [comment]
Has been added

**Comment by Wallby** [comment]
NOTE: looks like this is not in [U8glib-HAL-0.4.5](https://github.com/MarlinFirmware/U8glib-HAL/releases/tag/0.4.5) or earlier. I copied the library.properties from [U8glib-HAL-0.5.0](https://github.com/MarlinFirmware/U8glib-HAL/releases/tag/0.5.0) for use with 0.4.5, which worked.
